workflowWithTests = [
  '.*Widget Tests.*',
]

screenshotsDiffsPaths = [
  '.*expected.*',
  '.*new.*',
]

newScreenshotMark = '.*new/.*\.png'

branchesIgnore = []

screenshotImageAttrs = ['height="300px"']