workflowWithTests = [
  '.*Widget Tests.*',
]

screenshotsDiffsPaths = [
  '.*expected/.*.png',
]

newScreenshotMark = [
  '.*new/.*.png'
]

branchesIgnore = []

screenshotImageAttrs = ['height="300px"']