workflowWithTests = [
  '.*Widget Tests.*',
]

screenshotsDiffsPaths = [
  '.*expected/.*',
  '.*new/.*',
]

newScreenshotMark = '*.png'

branchesIgnore = []

screenshotImageAttrs = ['height="300px"']