workflowWithTests = [
  '.*Widget Tests.*',
]

screenshotsDiffsPaths = [
  '.*packages/widget/__tests__/Widget/expected/.*',
]

newScreenshotMark = '.*packages/widget/__tests__/Widget/new/.*'

branchesIgnore = []

screenshotImageAttrs = ['height="300px"']