name: automerge
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: 'pascalgn/automerge-action@v0.16.3'
        permissions:
          contents: write
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_METHOD: 'squash'
          MERGE_FILTER_AUTHOR: 'github-actions[bot]'
