name: Syncing branches
on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches (${{ matrix.to_branch }})
    strategy:
      fail-fast: false
      matrix:
        to_branch: [staging, dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.PERSONAL_TOKEN}}
          FROM_BRANCH: 'main'
          TO_BRANCH: ${{ matrix.to_branch }}
          CONTENT_COMPARISON: true
