name: Sync (staging)
on:
  pull_request:
    branches: [main]
    types: [closed]
  push:
    branches: [main]
  repository_dispatch:
    types: [sync-staging]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: staging

      - id: merge-main-to-staging
        name: Merge 'main' → 'staging'
        run: git merge --no-ff main

      - id: push-staging
        name: Push latest 'staging'
        run: git push --set-upstream origin staging
