name: TestingPRNumber

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  actions: write
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get PR Number by Author
        id: get-pr-number
        run: |
          PR_URL=$(gh pr list --author "toddkao" --json url --jq '.[0].url')
          PR_NUMBER=$(echo $PR_URL | grep -o '[0-9]*$')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "The PR number is: $PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: automerge
        uses: 'pascalgn/automerge-action@v0.16.3'
        continue-on-error: true
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_METHOD: 'squash'
          PULL_REQUEST: ${{ env.PR_NUMBER }}
