name: Widget Tests
on:
  pull_request:
  push:
    branches:
      - main
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Fetch submodule
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: yarn

  e2e-test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-noble
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_interval: 15
          max_timeout: 1200
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - run: git config --system --add safe.directory /__w/skip-go
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          WORD_PHRASE_KEY: ${{ secrets.WORD_PHRASE_KEY }}
          POLKACHU_USER: ${{ secrets.WORD_PHRASE_KEY }}
          POLKACHU_PASSWORD: ${{ secrets.POLKACHU_PASSWORD }}
          NEXT_PUBLIC_EDGE_CONFIG: ${{ secrets.NEXT_PUBLIC_EDGE_CONFIG }}
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitFor200.outputs.url }}
        run: xvfb-run --auto-servernum --server-args='-screen 0, 1920x1080x24' yarn run test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30